version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: docker_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_
      MYSQL_DATABASE: remedios
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
