name: CI - Spring Boot Project

on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_
          MYSQL_DATABASE: at
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Wait for MySQL to be ready
      run: |
        until docker exec docker_mysql mysqladmin ping -proot_ --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Build and Test with Maven
      run: mvn clean install -DskipTests=false

    - name: Check for Unused Imports
      run: mvn clean compile -DunusedDeclared=true
      continue-on-error: true

    - name: Remove Unused Imports
      if: failure()
      run: mvn com.github.hazendaz:unused-declared-maven-plugin:1.1.0:unusedDeclared

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Deploy to Production
      run: |
        echo "Deploy logic goes here"
